# Site settings
author: Diana Whalen
title: Adventures in Code
header-img: img/home-bg.png
email: whalendianaj@gmail.com
copyright_name: Diana Whalen
description: > # this means to ignore newlines until "baseurl:"
  My journey to becoming a software developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dianawhalen

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
